
platform :ios, '8.0'

target 'YandexMobileMetricaPushSampleObjC' do

    pod 'YandexMobileMetrica'
    pod 'YandexMobileMetricaPush'

end

target 'YandexMobileMetricaPushNotificationServiceExtenstionSampleObjC' do

    pod 'YandexMobileMetricaPush'

end
