
platform :ios, '8.0'

target 'YandexMobileMetricaPushSampleObjC' do

    pod 'YandexMobileMetrica', '~> 3.4'
    pod 'YandexMobileMetricaPush'

end

target 'YandexMobileMetricaPushNotificationServiceExtenstionSampleObjC' do

    pod 'YandexMobileMetricaPush'

end
