
platform :ios, '8.0'
# use_frameworks!

### For dynamic frameworks use:
#
#   pod 'YandexMobileMetrica/Dynamic'
#   pod 'YandexMobileMetricaPush/Dynamic'
#

target 'YandexMobileMetricaPushSampleSwift' do

    pod 'YandexMobileMetrica', '~> 3.4'
    pod 'YandexMobileMetricaPush'

end

target 'YandexMobileMetricaPushNotificationServiceExtenstionSampleSwift' do

    pod 'YandexMobileMetricaPush'

end